(function(){
  "use strict";
  var S=window.SS;if(!S)return;
  var BUCKET='business-files';
  var allowed=['image/jpeg','image/png','image/webp','application/pdf','model/stl','application/sla','application/vnd.ms-pki.stl','application/octet-stream','text/plain'];
  function safeName(name){return String(name||'arquivo').replace(/[^a-zA-Z0-9._-]+/g,'-').slice(-120);}
  S.renderAttachmentsPanel=async function(entityType,entityId,targetId){
    var el=document.getElementById(targetId);if(!el)return;
    var res=await S.sb.from('attachments').select('*').eq('organization_id',S.state.orgId).eq('entity_type',entityType).eq('entity_id',entityId).order('created_at',{ascending:false});if(res.error)throw res.error;var rows=res.data||[];
    el.innerHTML=(S.canWrite()?'<label class="dropzone"><strong>Adicionar arquivo</strong><span>Imagens, PDF, STL/3MF e arquivos permitidos até 25 MB.</span><input data-attachment-input type="file" data-entity-type="'+entityType+'" data-entity-id="'+entityId+'" data-target="'+targetId+'"></label>':'')+'<div class="compact-list" style="margin-top:10px">'+(rows.length?rows.map(function(a){return '<div class="attachment-row"><span><strong>'+S.e(a.original_filename)+'</strong><small class="muted">'+Math.max(1,Math.round(Number(a.size_bytes||0)/1024))+' KB · '+S.dt(a.created_at)+'</small></span><span class="actions"><button class="secondary mini" data-modular-action="download-attachment" data-path="'+S.e(a.storage_path)+'">Abrir</button>'+(S.canWrite()?'<button class="danger-btn mini" data-modular-action="delete-attachment" data-id="'+a.id+'" data-path="'+S.e(a.storage_path)+'" data-entity-type="'+entityType+'" data-entity-id="'+entityId+'" data-target="'+targetId+'">Excluir</button>':'')+'</span></div>';}).join(''):'<div class="muted">Nenhum arquivo anexado.</div>')+'</div>';
  };
  async function upload(input){
    var file=input.files&&input.files[0];if(!file)return;
    var ext=(file.name.split('.').pop()||'').toLowerCase();var special=['stl','3mf'];if(allowed.indexOf(file.type)===-1&&special.indexOf(ext)===-1)throw new Error('Tipo de arquivo não permitido.');if(file.size>25*1024*1024)throw new Error('O arquivo deve ter no máximo 25 MB.');
    var entityType=input.dataset.entityType,entityId=input.dataset.entityId;var path=S.state.orgId+'/'+entityType+'/'+entityId+'/'+Date.now()+'-'+safeName(file.name);
    input.disabled=true;var up=await S.sb.storage.from(BUCKET).upload(path,file,{contentType:file.type||'application/octet-stream',upsert:false});if(up.error){input.disabled=false;throw up.error;}
    var meta=await S.sb.from('attachments').insert({organization_id:S.state.orgId,entity_type:entityType,entity_id:entityId,storage_path:path,original_filename:file.name,mime_type:file.type||null,size_bytes:file.size,uploaded_by:S.state.session.user.id});if(meta.error){await S.sb.storage.from(BUCKET).remove([path]);input.disabled=false;throw meta.error;}
    input.value='';input.disabled=false;S.toast('Arquivo anexado.');await S.renderAttachmentsPanel(entityType,entityId,input.dataset.target);
  }
  S.openPaymentProofs=async function(orderId){var res=await S.sb.from('financial_transactions').select('id,amount,payment_method,paid_at,status,description').eq('organization_id',S.state.orgId).eq('order_id',orderId).eq('kind','income').order('paid_at',{ascending:false});if(res.error)throw res.error;var rows=res.data||[];S.modal('Comprovantes de pagamento','<div class="compact-list">'+(rows.length?rows.map(function(p){return '<div><strong>'+S.money(p.amount)+' · '+S.e((S.paymentMethodLabel?S.paymentMethodLabel(p.payment_method):p.payment_method)||'Não informado')+'</strong><small class="muted">'+S.dt(p.paid_at)+'</small><div id="paymentAttachments-'+p.id+'" style="margin-top:10px"></div></div>';}).join(''):'<div class="muted">Nenhum pagamento registrado.</div>')+'</div>',true);for(var i=0;i<rows.length;i++)await S.renderAttachmentsPanel('payment',rows[i].id,'paymentAttachments-'+rows[i].id);};
  document.addEventListener('change',async function(ev){var input=ev.target.closest('[data-attachment-input]');if(!input)return;try{await upload(input);}catch(err){input.disabled=false;S.toast(S.errText(err),'error');}});
  document.addEventListener('click',async function(ev){var b=ev.target.closest('[data-modular-action]');if(!b)return;try{if(b.dataset.modularAction==='download-attachment'){var s=await S.sb.storage.from(BUCKET).createSignedUrl(b.dataset.path,120);if(s.error)throw s.error;window.open(s.data.signedUrl,'_blank','noopener');}else if(b.dataset.modularAction==='delete-attachment'){if(!confirm('Excluir este arquivo?'))return;var rm=await S.sb.storage.from(BUCKET).remove([b.dataset.path]);if(rm.error)throw rm.error;var del=await S.sb.from('attachments').delete().eq('id',b.dataset.id).eq('organization_id',S.state.orgId);if(del.error)throw del.error;S.toast('Arquivo excluído.');await S.renderAttachmentsPanel(b.dataset.entityType,b.dataset.entityId,b.dataset.target);}else if(b.dataset.modularAction==='payment-proofs')await S.openPaymentProofs(b.dataset.orderId);}catch(err){S.toast(S.errText(err),'error');}});
  var baseShowOrder=S.showOrder;if(baseShowOrder)S.showOrder=async function(id){await baseShowOrder(id);var body=document.querySelector('.modal .modal-body');if(!body)return;body.insertAdjacentHTML('beforeend','<div class="section-title">Arquivos do pedido</div><div id="orderAttachments"></div><div class="actions" style="margin-top:10px"><button class="secondary" data-modular-action="payment-proofs" data-order-id="'+id+'">Comprovantes de pagamento</button></div>');await S.renderAttachmentsPanel('order',id,'orderAttachments');};
})();
