(function(){
  "use strict";
  var S=window.SS;if(!S)return;
  var basePage=S.pageBackup,baseValidate=S.validateWorkspaceBackup,basePreview=S.openBackupRestorePreview;
  var BUCKET='business-files';
  var modularSections=['quotes','quote_items','customer_product_prices','production_stages','order_production','production_stage_history','order_costs','attachments','notifications','filament_rolls','filament_movements','order_3d_details','generated_documents','email_outbox','client_mutations','sync_conflicts'];
  async function buildSnapshot(){
    if(S.state.role!=='owner')throw new Error('Somente o proprietário pode gerar o backup completo.');
    var org=S.currentOrg();var baseTables=['stores','customers','products','orders','order_items','inventory_movements','financial_transactions','audit_logs'];
    var jobs=baseTables.concat(modularSections).map(function(t){return S.fetchAll(t,'*','created_at').catch(function(err){if(t==='order_production'||t==='order_3d_details')return S.fetchAll(t,'*','updated_at');throw err;});});
    jobs.push(S.sb.rpc('list_team_members',{p_org:S.state.orgId}));jobs.push(S.sb.from('organization_settings').select('*').eq('organization_id',S.state.orgId).maybeSingle());
    var rows=await Promise.all(jobs);var teamRes=rows[baseTables.length+modularSections.length],settingsRes=rows[baseTables.length+modularSections.length+1];if(teamRes.error)throw teamRes.error;if(settingsRes.error)throw settingsRes.error;var snapshot={format:'system-seller-workspace-backup',schema_version:2,exported_at:new Date().toISOString(),organization:org,organization_settings:settingsRes.data||{organization_id:S.state.orgId},team:(teamRes.data||[]).map(function(m){return {membership_id:m.membership_id,user_id:m.user_id,full_name:m.full_name||null,role:m.role,created_at:m.created_at};})};
    baseTables.forEach(function(t,i){snapshot[t]=rows[i];});modularSections.forEach(function(t,i){snapshot[t]=rows[baseTables.length+i];});snapshot.file_manifest=(snapshot.attachments||[]).map(function(a){return {storage_path:a.storage_path,original_filename:a.original_filename,mime_type:a.mime_type,size_bytes:a.size_bytes,included:false};});return snapshot;
  }
  function saveBlob(name,blob){var url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1000);}
  S.downloadWorkspaceBackup=async function(){var snap=await buildSnapshot();saveBlob('system-seller-backup-'+S.todayIso()+'.json',new Blob([JSON.stringify(snap,null,2)],{type:'application/json;charset=utf-8'}));try{localStorage.setItem('systemSeller:lastBackup:'+S.state.orgId,snap.exported_at);}catch(e){}return snap;};
  S.downloadPortableBackup=async function(){if(!window.JSZip)throw new Error('Componente ZIP não carregado.');var snap=await buildSnapshot(),zip=new JSZip(),manifest=[];for(var i=0;i<(snap.attachments||[]).length;i++){var a=snap.attachments[i],entry={storage_path:a.storage_path,original_filename:a.original_filename,mime_type:a.mime_type,size_bytes:a.size_bytes,included:false};try{var signed=await S.sb.storage.from(BUCKET).createSignedUrl(a.storage_path,120);if(signed.error)throw signed.error;var res=await fetch(signed.data.signedUrl,{cache:'no-store'});if(!res.ok)throw new Error('HTTP '+res.status);zip.file('files/'+a.storage_path,await res.arrayBuffer());entry.included=true;}catch(err){entry.error=String(err&&err.message||err);}manifest.push(entry);}snap.file_manifest=manifest;zip.file('backup.json',JSON.stringify(snap,null,2));var blob=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}});saveBlob('system-seller-portable-'+S.todayIso()+'.zip',blob);var missing=manifest.filter(function(x){return !x.included;}).length;S.toast(missing?'Backup ZIP criado com '+missing+' arquivo(s) ausente(s); isso está registrado no manifesto.':'Backup portátil ZIP criado.');return snap;};
  S.validateWorkspaceBackup=function(snapshot){if(snapshot&&snapshot.schema_version===1)return baseValidate(snapshot);if(!snapshot||snapshot.format!=='system-seller-workspace-backup'||snapshot.schema_version!==2)throw new Error('Este arquivo não é um backup compatível do System Seller.');if(!snapshot.organization||!snapshot.organization.id||!snapshot.organization.name)throw new Error('O backup não possui uma empresa válida.');['stores','customers','products','orders','order_items','inventory_movements','financial_transactions','audit_logs','team'].concat(modularSections).forEach(function(k){if(!Array.isArray(snapshot[k]))throw new Error('Seção inválida no backup: '+k+'.');if(snapshot[k].length>100000)throw new Error('A seção '+k+' excede o limite permitido.');});return snapshot;};
  S.openBackupRestorePreview=function(snapshot){if(snapshot.schema_version===1)return basePreview(snapshot);var source=snapshot.organization||{},rows=[['Lojas',snapshot.stores.length],['Clientes',snapshot.customers.length],['Produtos',snapshot.products.length],['Pedidos',snapshot.orders.length],['Orçamentos',snapshot.quotes.length],['Etapas/histórico',snapshot.production_stage_history.length],['Custos',snapshot.order_costs.length],['Anexos',snapshot.attachments.length],['Rolos 3D',snapshot.filament_rolls.length],['Documentos',snapshot.generated_documents.length]].map(function(x){return '<div class="statline"><span>'+S.e(x[0])+'</span><strong>'+x[1]+'</strong></div>';}).join('');S.modal('Confirmar restauração v2','<div class="note"><strong>Empresa:</strong> '+S.e(source.name)+'<br><strong>Gerado em:</strong> '+S.e(snapshot.exported_at?S.dt(snapshot.exported_at):'Data não informada')+'<br><strong>Formato:</strong> backup v2'+(S.state.pendingBackupArchive?' + arquivos ZIP':' JSON')+'</div><div class="section-title">Conteúdo</div>'+rows+'<div class="note backup-warning"><strong>Atenção:</strong> a operação substitui os dados restauráveis da empresa atual e é restrita ao proprietário.</div><form data-modular-form="restore-v2"><div class="field"><label>Digite RESTAURAR</label><input name="confirmation" autocomplete="off" required></div><button class="danger-btn" type="submit">Restaurar backup v2</button></form>',true);};
  async function loadBackupFile(file){if(/\.zip$/i.test(file.name)){if(!window.JSZip)throw new Error('Componente ZIP não carregado.');var zip=await JSZip.loadAsync(file),entry=zip.file('backup.json');if(!entry)throw new Error('O ZIP não contém backup.json.');var snap=JSON.parse(await entry.async('text'));S.state.pendingBackup=S.validateWorkspaceBackup(snap);S.state.pendingBackupArchive=zip;}else{var snapJson=JSON.parse(await file.text());S.state.pendingBackup=S.validateWorkspaceBackup(snapJson);S.state.pendingBackupArchive=null;}S.openBackupRestorePreview(S.state.pendingBackup);}
  async function restoreFiles(zip,snapshot){if(!zip)return {uploaded:0,missing:0};var uploaded=0,missing=0;for(var i=0;i<(snapshot.file_manifest||[]).length;i++){var m=snapshot.file_manifest[i];if(!m.included){missing++;continue;}var entry=zip.file('files/'+m.storage_path);if(!entry){missing++;continue;}try{var data=await entry.async('arraybuffer');var up=await S.sb.storage.from(BUCKET).upload(m.storage_path,data,{contentType:m.mime_type||'application/octet-stream',upsert:true});if(up.error)throw up.error;uploaded++;}catch(e){missing++;}}return {uploaded:uploaded,missing:missing};}
  if(basePage)S.pageBackup=async function(){await basePage();var head=document.querySelector('#page .page-head .actions');if(head&&!head.querySelector('[data-modular-action="backup-full"]'))head.insertAdjacentHTML('beforeend','<button class="secondary" data-modular-action="backup-full">Baixar backup completo ZIP</button>');var input=document.getElementById('backupFileInput');if(input)input.setAttribute('accept','application/json,.json,application/zip,.zip');var text=document.querySelector('#page .backup-restore .muted');if(text)text.textContent='O proprietário pode restaurar JSON v1/v2 ou o ZIP portátil v2. O ZIP inclui os arquivos privados quando disponíveis.';};
  document.addEventListener('click',async function(ev){var b=ev.target.closest('[data-modular-action="backup-full"]');if(!b)return;try{b.disabled=true;await S.downloadPortableBackup();}catch(err){S.toast(S.errText(err),'error');}finally{b.disabled=false;}});
  document.addEventListener('change',async function(ev){var input=ev.target;if(input.id!=='backupFileInput')return;ev.stopImmediatePropagation();var file=input.files&&input.files[0];if(!file)return;try{input.disabled=true;if(file.size>250*1024*1024)throw new Error('O arquivo de backup excede 250 MB.');await loadBackupFile(file);}catch(err){S.toast(S.errText(err),'error');}finally{input.disabled=false;input.value='';}},{capture:true});
  document.addEventListener('submit',async function(ev){var form=ev.target.closest('form[data-modular-form="restore-v2"]');if(!form)return;ev.preventDefault();if(S.state.role!=='owner')return S.toast('Somente o proprietário pode restaurar backups.','error');S.busy(form,true);try{var f=Object.fromEntries(new FormData(form).entries());if(String(f.confirmation||'').trim().toUpperCase()!=='RESTAURAR')throw new Error('Digite RESTAURAR para confirmar.');var snap=S.validateWorkspaceBackup(S.state.pendingBackup);var r=await S.sb.rpc('restore_workspace_backup_v2',{p_organization_id:S.state.orgId,p_backup:snap});if(r.error)throw r.error;var files=await restoreFiles(S.state.pendingBackupArchive,snap);S.state.pendingBackup=null;S.state.pendingBackupArchive=null;S.state.data={};S.closeModal();await S.loadContext();S.toast('Backup v2 restaurado. Arquivos enviados: '+files.uploaded+(files.missing?' · ausentes/falhos: '+files.missing:'')+'.');}catch(err){S.toast(S.errText(err),'error');}finally{if(document.body.contains(form))S.busy(form,false);}});
})();
