(function(){
  "use strict";
  var S=window.SS;if(!S)return;
  S.profitForOrder=function(total,costs){return Number(total||0)-Number(costs||0);};
  var cats={material:'Material',packaging:'Embalagem',shipping:'Frete pago pela empresa',fees:'Taxas',labor:'Mão de obra',other:'Outros'};
  S.pageCosts=async function(){
    var page=document.getElementById('page');
    if(!S.canAdmin())throw new Error('Acesso restrito à administração.');
    var parts=await Promise.all([
      S.sb.from('order_costs').select('*').eq('organization_id',S.state.orgId).order('occurred_on',{ascending:false}),
      S.sb.from('orders').select('id,external_id,total,status,customer_id,sold_at').eq('organization_id',S.state.orgId).neq('status','cancelled').order('sold_at',{ascending:false}),
      S.getCore()
    ]);if(parts[0].error)throw parts[0].error;if(parts[1].error)throw parts[1].error;
    var costs=parts[0].data||[],orders=parts[1].data||[],core=parts[2],om={},cm={};orders.forEach(function(o){om[o.id]=o;});core.customers.forEach(function(c){cm[c.id]=c.name;});
    var revenue=orders.reduce(function(a,o){return a+Number(o.total||0);},0);var totalCosts=costs.reduce(function(a,c){return a+Number(c.amount||0);},0);var profit=S.profitForOrder(revenue,totalCosts);var margin=revenue?profit/revenue*100:0;
    page.innerHTML='<div class="page-head"><div><h2>Custos e lucro</h2><p>Custos operacionais separados do preço de venda.</p></div><button class="primary" data-modular-action="new-cost">+ Registrar custo</button></div>'+
      '<div class="metric-row"><div class="metric"><small>Vendas registradas</small><strong>'+S.money(revenue)+'</strong></div><div class="metric"><small>Custos registrados</small><strong>'+S.money(totalCosts)+'</strong></div><div class="metric"><small>Lucro bruto</small><strong class="'+(profit>=0?'profit-positive':'profit-negative')+'">'+S.money(profit)+'</strong></div><div class="metric"><small>Margem bruta</small><strong>'+margin.toFixed(1)+'%</strong></div></div>'+
      '<div class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Pedido</th><th>Cliente</th><th>Categoria</th><th>Descrição</th><th>Valor</th><th></th></tr></thead><tbody>'+
      (costs.length?costs.map(function(c){var o=om[c.order_id]||{};return '<tr><td>'+S.day(c.occurred_on)+'</td><td>'+S.e(o.external_id||('#'+String(c.order_id).slice(0,8)))+'</td><td>'+S.e(cm[o.customer_id]||'—')+'</td><td>'+S.e(cats[c.category]||c.category)+'</td><td>'+S.e(c.description||'—')+'</td><td>'+S.money(c.amount)+'</td><td><button class="link-btn" data-modular-action="delete-cost" data-id="'+c.id+'">Excluir</button></td></tr>';}).join(''):'<tr><td colspan="7"><div class="empty"><strong>Nenhum custo registrado</strong>Adicione materiais, fretes, taxas e mão de obra.</div></td></tr>')+'</tbody></table></div></div>';
  };
  async function openCost(){
    var parts=await Promise.all([S.sb.from('orders').select('id,external_id,customer_id').eq('organization_id',S.state.orgId).neq('status','cancelled').order('created_at',{ascending:false}),S.sb.from('order_items').select('id,order_id,name,sku').eq('organization_id',S.state.orgId).order('created_at'),S.getCore()]);if(parts[0].error)throw parts[0].error;if(parts[1].error)throw parts[1].error;var orders=parts[0].data||[],items=parts[1].data||[],core=parts[2],cm={};core.customers.forEach(function(c){cm[c.id]=c.name;});var opts=orders.map(function(o){return '<option value="'+o.id+'">'+S.e((o.external_id||('#'+o.id.slice(0,8)))+' · '+(cm[o.customer_id]||'Sem cliente'))+'</option>';}).join('');var iopts='<option value="">Pedido inteiro</option>'+items.map(function(x){var o=orders.find(function(v){return v.id===x.order_id;});return '<option value="'+x.id+'" data-order="'+x.order_id+'">'+S.e((o&&o.external_id?o.external_id:o?('#'+o.id.slice(0,8)):'Pedido')+' · '+x.sku+' · '+x.name)+'</option>';}).join('');
    S.modal('Registrar custo','<form data-modular-form="cost"><div class="field"><label>Pedido</label><select name="order_id" required><option value="">Selecione</option>'+opts+'</select></div><div class="field"><label>Item específico (opcional)</label><select name="order_item_id">'+iopts+'</select></div><div class="form-grid"><div class="field"><label>Categoria</label><select name="category">'+Object.keys(cats).map(function(k){return '<option value="'+k+'">'+cats[k]+'</option>';}).join('')+'</select></div><div class="field"><label>Valor</label><input name="amount" type="number" min="0" step="0.01" required></div><div class="field"><label>Data</label><input name="occurred_on" type="date" value="'+S.todayIso()+'" required></div><div class="field"><label>Descrição</label><input name="description" maxlength="240"></div></div><button class="primary" type="submit">Registrar custo</button></form>',true);
  }
  document.addEventListener('click',async function(ev){var b=ev.target.closest('[data-modular-action]');if(!b)return;try{if(b.dataset.modularAction==='new-cost')await openCost();else if(b.dataset.modularAction==='delete-cost'){if(!confirm('Excluir este custo?'))return;var r=await S.sb.from('order_costs').delete().eq('id',b.dataset.id).eq('organization_id',S.state.orgId);if(r.error)throw r.error;S.toast('Custo excluído.');await S.pageCosts();}}catch(err){S.toast(S.errText(err),'error');}});
  document.addEventListener('submit',async function(ev){var form=ev.target.closest('form[data-modular-form="cost"]');if(!form)return;ev.preventDefault();S.busy(form,true);try{var f=Object.fromEntries(new FormData(form).entries());var amount=Number(f.amount);if(!f.order_id||amount<0)throw new Error('Revise os dados do custo.');var res=await S.sb.rpc('record_order_cost',{p_order_id:f.order_id,p_order_item_id:f.order_item_id||null,p_category:f.category,p_amount:amount,p_description:String(f.description||'').trim()||null,p_occurred_on:f.occurred_on||null});if(res.error)throw res.error;S.closeModal();S.toast('Custo registrado.');await S.pageCosts();}catch(err){S.toast(S.errText(err),'error');}finally{if(document.body.contains(form))S.busy(form,false);}});
})();
