(function(){
  "use strict";
  var S=window.SS;if(!S)return;
  S.collectionMessage=function(order,customer){var paid=Number(order.paid_amount||0),balance=Math.max(0,Number(order.total||0)-paid);return 'Olá'+(customer&&customer.name?', '+customer.name:'')+'! Referente ao pedido '+(order.external_id||('#'+order.id.slice(0,8)))+', o valor total é '+S.money(order.total)+', já recebemos '+S.money(paid)+' e o saldo restante é '+S.money(balance)+(order.balance_due_at?' com vencimento em '+S.day(order.balance_due_at):'')+'.';};
  async function upsertNotice(n){var r=await S.sb.from('notifications').upsert(n,{onConflict:'organization_id,dedupe_key',ignoreDuplicates:true});if(r.error)throw r.error;}
  S.refreshOperationalNotifications=async function(){
    if(!S.state.orgId)return;var today=S.todayIso(),cfg=await S.ensureOrgSettings();var parts=await Promise.all([
      S.sb.from('orders').select('id,external_id,due_at,total,paid_amount,payment_status,status,balance_due_at').eq('organization_id',S.state.orgId).neq('status','cancelled'),
      S.sb.from('products').select('id,name,stock,min_stock').eq('organization_id',S.state.orgId).eq('active',true),
      S.sb.from('order_production').select('order_id,stage_id,updated_at').eq('organization_id',S.state.orgId),
      S.sb.from('production_stages').select('id,name').eq('organization_id',S.state.orgId),
      cfg.enable_3d?S.sb.from('filament_rolls').select('id,material,color,remaining_weight_g,status').eq('organization_id',S.state.orgId).eq('status','active'):Promise.resolve({data:[],error:null})
    ]);for(var i=0;i<parts.length;i++)if(parts[i].error)throw parts[i].error;var orders=parts[0].data||[],products=parts[1].data||[],prod=parts[2].data||[],stages=parts[3].data||[],rolls=parts[4].data||[],sm={};stages.forEach(function(x){sm[x.id]=x.name;});var now=Date.now();
    var notices=[];orders.forEach(function(o){var label=o.external_id||('#'+o.id.slice(0,8)),balance=Math.max(0,Number(o.total||0)-Number(o.paid_amount||0));if(o.due_at&&new Date(o.due_at).getTime()<now&&o.status!=='delivered')notices.push({event_type:'overdue_order',entity_type:'order',entity_id:String(o.id),dedupe_key:'overdue:'+o.id+':'+today,title:'Pedido atrasado',body:label+' passou do prazo de entrega.',severity:'danger'});else if(o.due_at&&new Date(o.due_at).getTime()-now<48*3600000&&new Date(o.due_at).getTime()>now&&o.status!=='delivered')notices.push({event_type:'due_soon',entity_type:'order',entity_id:String(o.id),dedupe_key:'due-soon:'+o.id+':'+today,title:'Entrega próxima',body:label+' vence em menos de 48 horas.',severity:'warning'});if(balance>0&&(o.payment_status==='pending'||o.payment_status==='partial'))notices.push({event_type:'outstanding_payment',entity_type:'order',entity_id:String(o.id),dedupe_key:'balance:'+o.id+':'+today,title:'Pagamento pendente',body:label+' possui '+S.money(balance)+' em aberto.',severity:'warning'});});products.forEach(function(p){if(Number(p.stock)<=Number(p.min_stock))notices.push({event_type:'low_inventory',entity_type:'product',entity_id:String(p.id),dedupe_key:'low-product:'+p.id+':'+today,title:'Estoque baixo',body:p.name+' está com '+p.stock+' unidade(s).',severity:'warning'});});rolls.forEach(function(r){if(Number(r.remaining_weight_g)<=Number(cfg.low_filament_threshold_g||0))notices.push({event_type:'low_filament',entity_type:'filament_roll',entity_id:String(r.id),dedupe_key:'low-filament:'+r.id+':'+today,title:'Filamento baixo',body:r.material+' '+r.color+' está com '+Number(r.remaining_weight_g).toFixed(0)+' g.',severity:'warning'});});prod.forEach(function(p){if(p.stage_id&&p.updated_at&&now-new Date(p.updated_at).getTime()>Number(cfg.stalled_stage_hours||72)*3600000)notices.push({event_type:'stalled_production',entity_type:'order',entity_id:String(p.order_id),dedupe_key:'stalled:'+p.order_id+':'+today,title:'Produção parada',body:'Pedido em '+(sm[p.stage_id]||'uma etapa')+' sem atualização pelo período configurado.',severity:'warning'});});
    for(var j=0;j<notices.length;j++){notices[j].organization_id=S.state.orgId;await upsertNotice(notices[j]);}return notices.length;
  };
  S.pageNotifications=async function(){var page=document.getElementById('page');await S.refreshOperationalNotifications();var parts=await Promise.all([S.sb.from('notifications').select('*').eq('organization_id',S.state.orgId).order('created_at',{ascending:false}).limit(200),S.canAdmin()?S.sb.from('email_outbox').select('*').eq('organization_id',S.state.orgId).order('created_at',{ascending:false}).limit(50):Promise.resolve({data:[],error:null}),S.sb.from('sync_conflicts').select('*').eq('organization_id',S.state.orgId).eq('status','open').order('created_at',{ascending:false})]);for(var i=0;i<parts.length;i++)if(parts[i].error)throw parts[i].error;var rows=parts[0].data||[],emails=parts[1].data||[],conflicts=parts[2].data||[];page.innerHTML='<div class="page-head"><div><h2>Notificações</h2><p>Alertas operacionais, cobranças, falhas de e-mail e conflitos offline.</p></div><button class="secondary" data-modular-action="refresh-notifications">Atualizar alertas</button></div><div class="metric-row"><div class="metric"><small>Não lidas</small><strong>'+rows.filter(function(n){return !n.read_at;}).length+'</strong></div><div class="metric"><small>Conflitos offline</small><strong>'+conflicts.length+'</strong></div><div class="metric"><small>E-mails pendentes</small><strong>'+emails.filter(function(e){return e.status==='queued'||e.status==='sending';}).length+'</strong></div><div class="metric"><small>E-mails com falha</small><strong>'+emails.filter(function(e){return e.status==='failed';}).length+'</strong></div></div><div class="grid2"><div class="panel"><div class="panel-head"><h3>Central de alertas</h3></div><div class="panel-body compact-list">'+(rows.length?rows.map(function(n){return '<div class="notice '+S.e(n.severity||'')+' '+(!n.read_at?'notification-unread':'')+'"><div style="display:flex;justify-content:space-between;gap:10px"><span><strong>'+S.e(n.title)+'</strong><small class="muted">'+S.e(n.body)+' · '+S.dt(n.created_at)+'</small></span>'+(!n.read_at?'<button class="ghost mini" data-modular-action="read-notification" data-id="'+n.id+'">Marcar lida</button>':'')+'</div></div>';}).join(''):'<div class="muted">Nenhuma notificação.</div>')+'</div></div><div class="panel"><div class="panel-head"><h3>E-mails</h3></div><div class="panel-body compact-list">'+(emails.length?emails.map(function(e){return '<div><strong>'+S.e(e.recipient)+'</strong><small class="muted">'+S.e(e.subject)+' · '+S.e(e.status)+(e.last_error?' · '+S.e(e.last_error):'')+'</small>'+(e.status!=='sent'?'<button class="secondary mini" data-modular-action="send-outbox" data-id="'+e.id+'">Enviar / tentar novamente</button>':'')+'</div>';}).join(''):'<div class="muted">Nenhum e-mail na fila.</div>')+'</div></div></div>';
  };
  S.sendOutbox=async function(id){var r=await S.sb.functions.invoke('process-business-email',{body:{outbox_id:id}});if(r.error)throw r.error;if(r.data&&r.data.error)throw new Error(r.data.error==='email_provider_not_configured'?'A chave BREVO_API_KEY ainda não está configurada nos segredos do Supabase.':r.data.error);return r.data;};
  async function loadOrderContext(id){var parts=await Promise.all([S.sb.from('orders').select('*').eq('id',id).eq('organization_id',S.state.orgId).single(),S.getCore()]);if(parts[0].error)throw parts[0].error;var o=parts[0].data,c=parts[1].customers.find(function(x){return x.id===o.customer_id;});return {order:o,customer:c};}
  S.openCollectionTools=async function(orderId){var x=await loadOrderContext(orderId),msg=S.collectionMessage(x.order,x.customer);S.modal('Cobrança do pedido','<div class="field"><label>Mensagem para o cliente</label><textarea id="collectionMessage" rows="7" readonly>'+S.e(msg)+'</textarea></div><div class="actions"><button class="secondary" data-modular-action="copy-collection">Copiar mensagem</button>'+(x.customer&&x.customer.email?'<button class="primary" data-modular-action="email-collection" data-order-id="'+x.order.id+'">Enviar por e-mail para '+S.e(x.customer.email)+'</button>':'')+'</div><div class="section-title">Vencimento do saldo</div><form data-modular-form="balance-due" data-order-id="'+x.order.id+'"><div class="field"><label>Data/hora</label><input name="due_at" type="datetime-local" value="'+S.localInput(x.order.balance_due_at)+'"></div><button class="primary" type="submit">Salvar vencimento</button></form>');};
  document.addEventListener('click',async function(ev){var b=ev.target.closest('[data-modular-action]');if(!b)return;try{var a=b.dataset.modularAction;if(a==='refresh-notifications'){await S.refreshOperationalNotifications();await S.pageNotifications();S.toast('Alertas atualizados.');}else if(a==='read-notification'){var r=await S.sb.from('notifications').update({read_at:new Date().toISOString()}).eq('id',b.dataset.id).eq('organization_id',S.state.orgId);if(r.error)throw r.error;await S.pageNotifications();}else if(a==='send-outbox'){await S.sendOutbox(b.dataset.id);S.toast('E-mail processado.');await S.pageNotifications();}else if(a==='collection-tools')await S.openCollectionTools(b.dataset.orderId);else if(a==='copy-collection'){var el=document.getElementById('collectionMessage');await navigator.clipboard.writeText(el.value);S.toast('Mensagem copiada.');}else if(a==='email-collection'){var x=await loadOrderContext(b.dataset.orderId);if(!x.customer||!x.customer.email)throw new Error('Cliente sem e-mail.');var msg=S.collectionMessage(x.order,x.customer);var q=await S.sb.rpc('queue_business_email',{p_organization_id:S.state.orgId,p_recipient:x.customer.email,p_subject:'Cobrança · '+(x.order.external_id||x.order.id.slice(0,8)),p_body:msg,p_related_type:'order',p_related_id:x.order.id});if(q.error)throw q.error;try{await S.sendOutbox(q.data);S.toast('Cobrança enviada por e-mail.');}catch(emailErr){S.toast(S.errText(emailErr),'error');}}}catch(err){S.toast(S.errText(err),'error');}});
  document.addEventListener('submit',async function(ev){var form=ev.target.closest('form[data-modular-form="balance-due"]');if(!form)return;ev.preventDefault();S.busy(form,true);try{var f=Object.fromEntries(new FormData(form).entries());var r=await S.sb.rpc('set_order_balance_due',{p_order_id:form.dataset.orderId,p_due_at:f.due_at?S.zonedInputToIso(f.due_at):null});if(r.error)throw r.error;S.toast('Vencimento atualizado.');S.closeModal();}catch(err){S.toast(S.errText(err),'error');}finally{if(document.body.contains(form))S.busy(form,false);}});
  var baseShowOrder=S.showOrder;if(baseShowOrder)S.showOrder=async function(id){await baseShowOrder(id);var body=document.querySelector('.modal .modal-body');if(body)body.insertAdjacentHTML('afterbegin','<div class="actions" style="margin-bottom:12px"><button class="secondary" data-modular-action="collection-tools" data-order-id="'+id+'">Cobrança / saldo</button></div>');};
})();
