(function(){
  "use strict";
  var S=window.SS;if(!S||!window.indexedDB)return;
  var DB="system-seller-operational-cache",STORE="snapshots",baseFetchAll=S.fetchAll,baseOrders=S.pageOrders,baseQuotes=S.pageQuotes,baseProduction=S.pageProduction,baseCalendar=S.pageCalendar;
  function cacheKey(org,key){return String(org||'none')+'::'+key;}
  function openDb(){return new Promise(function(resolve,reject){var r=indexedDB.open(DB,1);r.onupgradeneeded=function(){if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'key'});};r.onsuccess=function(){resolve(r.result);};r.onerror=function(){reject(r.error);};});}
  async function put(key,value){var db=await openDb();return new Promise(function(resolve,reject){var tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put({key:key,value:value,updated_at:new Date().toISOString()});tx.oncomplete=function(){resolve();};tx.onerror=function(){reject(tx.error);};});}
  async function get(key){var db=await openDb();return new Promise(function(resolve,reject){var tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).get(key);r.onsuccess=function(){resolve(r.result||null);};r.onerror=function(){reject(r.error);};});}
  S.cacheOperationalData=function(key,value){return put(cacheKey(S.state.orgId,key),value);};
  S.readOperationalData=async function(key){var row=await get(cacheKey(S.state.orgId,key));return row?row.value:null;};
  S.fetchAll=async function(table,columns,orderCol){var key='fetch:'+table+':'+String(columns||'*')+':'+String(orderCol===undefined?'created_at':orderCol);if(navigator.onLine){try{var rows=await baseFetchAll(table,columns,orderCol);await S.cacheOperationalData(key,rows);return rows;}catch(err){var cached=await S.readOperationalData(key);if(cached)return cached;throw err;}}var local=await S.readOperationalData(key);if(local)return local;throw new Error('Esses dados ainda não foram armazenados para uso offline. Abra esta área ao menos uma vez com internet.');};
  async function refreshSnapshot(){if(!navigator.onLine||!S.state.orgId)return null;var parts=await Promise.all([S.sb.from('orders').select('*').eq('organization_id',S.state.orgId).order('created_at',{ascending:false}).limit(500),S.sb.from('quotes').select('*').eq('organization_id',S.state.orgId).order('created_at',{ascending:false}).limit(500),S.sb.from('order_production').select('*').eq('organization_id',S.state.orgId),S.sb.from('production_stages').select('*').eq('organization_id',S.state.orgId).order('position'),S.getCore()]);for(var i=0;i<4;i++)if(parts[i].error)throw parts[i].error;var snap={cached_at:new Date().toISOString(),orders:parts[0].data||[],quotes:parts[1].data||[],production:parts[2].data||[],stages:parts[3].data||[],core:parts[4]};await S.cacheOperationalData('operational',snap);return snap;}
  function cachedHeader(snap){return '<div class="notice warning" style="margin-bottom:14px"><strong>Modo offline</strong><div class="muted">Exibindo dados armazenados em '+S.dt(snap.cached_at)+'. Alterações permitidas serão sincronizadas ao reconectar.</div></div>';}
  function orderName(o){return S.e(o.external_id||('#'+o.id.slice(0,8)));}
  async function offlineOrders(){var page=document.getElementById('page'),snap=await S.readOperationalData('operational');if(!snap)throw new Error('Nenhum snapshot operacional disponível offline. Abra Pedidos com internet primeiro.');var body=S.ordersTable?S.ordersTable(snap.orders,snap.core):'';var noteActions=S.canWrite()?'<div class="section-title">Notas operacionais offline</div><div class="compact-list">'+snap.orders.slice(0,30).map(function(o){return '<div><span><strong>'+orderName(o)+'</strong><small class="muted">'+S.e((snap.core.customers||[]).find(function(c){return c.id===o.customer_id;})?.name||'Sem cliente')+'</small></span><button class="secondary mini" data-modular-action="offline-order-note" data-id="'+o.id+'" data-base="'+S.e(o.updated_at||'')+'" data-notes="'+encodeURIComponent(o.notes||'')+'">Editar nota</button></div>';}).join('')+'</div>':'';page.innerHTML='<div class="page-head"><div><h2>Pedidos</h2><p>Dados operacionais armazenados para uso offline.</p></div>'+(S.canWrite()?'<button class="primary" data-action="new-order">+ Novo pedido offline</button>':'')+'</div>'+cachedHeader(snap)+body+noteActions;}
  async function offlineQuotes(){var page=document.getElementById('page'),snap=await S.readOperationalData('operational');if(!snap)throw new Error('Nenhum snapshot operacional disponível offline.');var cm={};(snap.core.customers||[]).forEach(function(c){cm[c.id]=c.name;});page.innerHTML='<div class="page-head"><div><h2>Orçamentos</h2><p>Dados armazenados para consulta offline.</p></div>'+(S.canWrite()?'<button class="primary" data-modular-action="new-quote">+ Novo orçamento offline</button>':'')+'</div>'+cachedHeader(snap)+'<div class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>Orçamento</th><th>Cliente</th><th>Status</th><th>Total</th><th>Criado</th></tr></thead><tbody>'+(snap.quotes.length?snap.quotes.map(function(q){return '<tr><td>#'+q.id.slice(0,8)+'</td><td>'+S.e(cm[q.customer_id]||'—')+'</td><td>'+S.e(q.status)+'</td><td>'+S.money(q.total)+'</td><td>'+S.dt(q.created_at)+'</td></tr>';}).join(''):'<tr><td colspan="5">Nenhum orçamento em cache.</td></tr>')+'</tbody></table></div></div>';}
  async function offlineProduction(){var page=document.getElementById('page'),snap=await S.readOperationalData('operational');if(!snap)throw new Error('Nenhum snapshot operacional disponível offline.');var pm={},cm={};snap.production.forEach(function(p){pm[p.order_id]=p;});(snap.core.customers||[]).forEach(function(c){cm[c.id]=c.name;});var opts=snap.stages.filter(function(s){return s.active;});var cards=snap.orders.filter(function(o){return o.status!=='cancelled'&&o.status!=='delivered';}).slice(0,50).map(function(o){var p=pm[o.id]||{};return '<form data-modular-form="offline-production" data-order-id="'+o.id+'" data-base="'+S.e(p.updated_at||'')+'" data-production="'+encodeURIComponent(JSON.stringify(p))+'" class="stage-card"><strong>'+orderName(o)+'</strong><small>'+S.e(cm[o.customer_id]||'Sem cliente')+'</small><div class="field" style="margin-top:8px"><label>Etapa</label><select name="stage_id"><option value="">Sem etapa</option>'+opts.map(function(s){return '<option value="'+s.id+'"'+(s.id===p.stage_id?' selected':'')+'>'+S.e(s.name)+'</option>';}).join('')+'</select></div><button class="secondary mini" type="submit">Salvar etapa offline</button></form>';}).join('');page.innerHTML='<div class="page-head"><div><h2>Produção</h2><p>Atualize etapas offline; conflitos serão sinalizados na sincronização.</p></div></div>'+cachedHeader(snap)+'<div class="stage-board">'+cards+'</div>';}
  async function offlineCalendar(){var page=document.getElementById('page'),snap=await S.readOperationalData('operational');if(!snap)throw new Error('Nenhum snapshot operacional disponível offline.');var pm={},sm={};snap.production.forEach(function(p){pm[p.order_id]=p;});snap.stages.forEach(function(s){sm[s.id]=s.name;});var list=snap.orders.filter(function(o){return o.due_at||pm[o.id]?.planned_finish;}).sort(function(a,b){return new Date((pm[a.id]&&pm[a.id].planned_finish)||a.due_at)-new Date((pm[b.id]&&pm[b.id].planned_finish)||b.due_at);}).slice(0,60).map(function(o){var p=pm[o.id]||{};return '<div class="list-item"><span><strong>'+orderName(o)+'</strong><small class="muted">'+S.e(sm[p.stage_id]||'Sem etapa')+'</small></span><strong>'+S.dt(p.planned_finish||o.due_at)+'</strong></div>';}).join('');page.innerHTML='<div class="page-head"><div><h2>Calendário</h2><p>Prazos armazenados para consulta offline.</p></div></div>'+cachedHeader(snap)+'<div class="panel"><div class="panel-body list">'+(list||'<div class="muted">Nenhum prazo armazenado.</div>')+'</div></div>';}
  if(baseOrders)S.pageOrders=async function(){if(!navigator.onLine)return offlineOrders();var out=await baseOrders();refreshSnapshot().catch(function(){});return out;};
  if(baseQuotes)S.pageQuotes=async function(){if(!navigator.onLine)return offlineQuotes();var out=await baseQuotes();refreshSnapshot().catch(function(){});return out;};
  if(baseProduction)S.pageProduction=async function(){if(!navigator.onLine)return offlineProduction();var out=await baseProduction();refreshSnapshot().catch(function(){});return out;};
  if(baseCalendar)S.pageCalendar=async function(){if(!navigator.onLine)return offlineCalendar();var out=await baseCalendar();refreshSnapshot().catch(function(){});return out;};
  document.addEventListener('click',function(ev){var b=ev.target.closest('[data-modular-action="offline-order-note"]');if(!b)return;S.modal('Nota operacional offline','<form data-modular-form="offline-order-note" data-order-id="'+b.dataset.id+'" data-base="'+S.e(b.dataset.base||'')+'"><div class="field"><label>Nota</label><textarea name="notes" maxlength="2000">'+S.e(decodeURIComponent(b.dataset.notes||''))+'</textarea></div><button class="primary" type="submit">Salvar na fila offline</button></form>');});
  document.addEventListener('submit',async function(ev){var form=ev.target.closest('form[data-modular-form="offline-order-note"],form[data-modular-form="offline-production"]');if(!form)return;ev.preventDefault();S.busy(form,true);try{if(!S.queueOfflineMutation)throw new Error('Fila offline indisponível.');if(form.dataset.modularForm==='offline-order-note'){var f=Object.fromEntries(new FormData(form).entries());await S.queueOfflineMutation('order_notes',{order_id:form.dataset.orderId,notes:f.notes||null},form.dataset.base||null);S.closeModal();S.toast('Nota adicionada à fila offline.');}else{var f2=Object.fromEntries(new FormData(form).entries()),p={};try{p=JSON.parse(decodeURIComponent(form.dataset.production||''))||{};}catch(e){}await S.queueOfflineMutation('production_update',{order_id:form.dataset.orderId,stage_id:f2.stage_id||null,planned_start:p.planned_start||null,planned_finish:p.planned_finish||null,estimated_minutes:p.estimated_minutes==null?null:Number(p.estimated_minutes),responsible_user_id:p.responsible_user_id||null,notes:p.notes||null},form.dataset.base||null);S.toast('Etapa adicionada à fila offline.');}}catch(err){S.toast(S.errText(err),'error');}finally{if(document.body.contains(form))S.busy(form,false);}});
  window.addEventListener('online',function(){refreshSnapshot().catch(function(){});});
})();
